### PR TITLE
Fixed the paging functionality and inner data handling.

### PR DESCRIPTION
**Pull request by shmaxi**
With the new GraphAPI versions, nested data may be returned.
For example, when accessing:
https://graph.facebook.com/v6.0/<profile_id>/groups?access_token=<access_token>

The return JSON is of this structure:
```javascript
{
  "groups": {
    "data": [
      {
        "name": "<group1 name>",
        "privacy": "CLOSED",
        "id": "<group1 id>"
      },
      {
        "name": "<group2 name>",
        "id": "<group2 id>"
      }
    ],
    "paging": {
      "cursors": {
        "before": "<previous cursor>",
        "after": "<next cursor>"
      },
      "next": "<next page>"
    }
  },
  "id": "<profile id>"
}
```

As you can see the root structure does not contain a "data" field, which
makes the pagination method to fail and think there's no paginated data.

### CODE REVIEW

**Comment by huandu** [comment]
Thanks for your contribution.

I try to use Facebook Graph API Explorer to reproduce your query result. I find that the only way is to [query `groups` with `fields=groups`](https://developers.facebook.com/tools/explorer?method=GET&path=me%2Fgroups&version=v6.0). It's not new in `v6.0`. It's an expected behavior since `v3`.

If you see such result when querying `https://graph.facebook.com/v6.0/<profile_id>/groups`, I recommend you to [Report a Bug](https://developers.facebook.com/support/bugs/) to Facebook. It's unexpected.

Regarding to the JSON structure, I recommend to decode it with following `struct`.

```go
type User struct {
    ID string
    Groups facebook.Result
}

var user User
err := res.Decode(&user)
groups, err := user.Groups.Paging(session)
```

**Comment by huandu** [comment]
If you can verify that the JSON structure is a feature rather than a bug, I will revisit this PR. If not, I'll close it.

**Comment by shmaxi** [comment]
@huandu Thank you so much for responding!
Now that you mention it, it looks like I've been using the API a bit differently than intended.
Instead of using :
https://graph.facebook.com/v6.0/<profile_id>/groups?access_token=<access_token>
I was using:
https://graph.facebook.com/v6.0/<profile_id>?fields=groups?access_token=<access_token>

This in turn returns a nested result, as I'm not accessing the edge of the profile node.
When accessing the groups resource via the edge and not the fields, the result was returning as expected.

You can close the PR.
Sorry to have bothered you and I thank you for the lesson 
😊
🙏🏻

**Comment by huandu** [comment]
You are welcome. 😄

**Pull request closed without merging**
